CREATE TABLE facult(
    id UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    CONSTRAINT facult_pkey PRIMARY KEY(id),
);

CREATE TABLE grp(
    id UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    CONSTRAINT grp_pkey PRIMARY KEY(id),
    FOREIGN KEY("facult_id") REFERENCES facult(id)
);

CREATE TABLE student(
    id UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstName varchar(100) NOT NULL,
    lastName varchar(100) NOT NULL,
    CONSTRAINT student_pkey PRIMARY KEY(id),
    FOREIGN KEY("grp_id") REFERENCES grp(id)
);
CREATE TABLE mark(
    id UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "date" DATE NOT NULL,
    discipline varchar(100) NOT NULL,
    mrk_value varchar(100) NOT NULL,
    CONSTRAINT mark_pkey PRIMARY KEY(id),
    FOREIGN KEY("student_id") REFERENCES student(id)
);